#!/usr/bin/env python3
"""
update_readme_index.py
Run from the root of the Psi-Wars-Ships repo.
Walks the project, builds raw GitHub URLs for every tracked file,
and injects (or updates) a '## File Index' section in README.md.

Usage:
    python update_readme_index.py

To auto-run on every commit, add to .git/hooks/pre-commit:
    #!/bin/sh
    python update_readme_index.py
    git add README.md
"""

import os
import subprocess

# ── Config ────────────────────────────────────────────────────────────────────
GITHUB_USER   = "Zerick"
GITHUB_REPO   = "Psi-Wars-Ships"
BRANCH        = "main"
README_PATH   = "README.md"
RAW_BASE      = f"https://raw.githubusercontent.com/{GITHUB_USER}/{GITHUB_REPO}/{BRANCH}"
GITHUB_BASE   = f"https://github.com/{GITHUB_USER}/{GITHUB_REPO}/blob/{BRANCH}"

# Files/dirs to skip
SKIP_DIRS  = {".git", "node_modules", "__pycache__", ".venv", "venv", "dist", ".next"}
SKIP_FILES = {".DS_Store", "*.pyc", "package-lock.json"}
SKIP_EXTS  = {".pyc", ".pyo", ".db", ".sqlite", ".sqlite3"}
# ──────────────────────────────────────────────────────────────────────────────


def get_git_tracked_files():
    """Return list of files tracked by git (respects .gitignore)."""
    try:
        result = subprocess.run(
            ["git", "ls-files"],
            capture_output=True, text=True, check=True
        )
        return sorted(result.stdout.strip().splitlines())
    except subprocess.CalledProcessError:
        return None


def walk_all_files():
    """Fallback: walk filesystem if git isn't available."""
    files = []
    for root, dirs, filenames in os.walk("."):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
        for fname in filenames:
            if any(fname.endswith(ext) for ext in SKIP_EXTS):
                continue
            path = os.path.join(root, fname).lstrip("./").replace("\\", "/")
            files.append(path)
    return sorted(files)


def build_index(file_list):
    """Build the markdown file index block."""
    lines = ["## File Index", "",
             "_Auto-generated by `update_readme_index.py` — do not edit this section manually._",
             ""]

    # Group by top-level directory
    groups = {}
    for f in file_list:
        parts = f.split("/")
        group = parts[0] if len(parts) > 1 else "(root)"
        groups.setdefault(group, []).append(f)

    for group in sorted(groups):
        lines.append(f"### `{group}/`" if group != "(root)" else "### (root)")
        for f in groups[group]:
            raw_url    = f"{RAW_BASE}/{f}"
            github_url = f"{GITHUB_BASE}/{f}"
            # Plain URL in code span so GitHub can't mangle it
            lines.append(f"- [`{f}`]({github_url}) · raw: `{raw_url}`")
        lines.append("")

    return "\n".join(lines)


def write_index_txt(file_list):
    """Write a plain FILE_INDEX.txt with one raw URL per line."""
    with open("FILE_INDEX.txt", "w", encoding="utf-8") as fh:
        fh.write("# Psi-Wars-Ships raw file URLs\n")
        fh.write("# Auto-generated by update_readme_index.py\n\n")
        for f in file_list:
            fh.write(f"{RAW_BASE}/{f}\n")
    print("FILE_INDEX.txt written.")


def update_readme(index_block):
    with open(README_PATH, "r", encoding="utf-8") as fh:
        content = fh.read()

    marker_start = "<!-- FILE_INDEX_START -->"
    marker_end   = "<!-- FILE_INDEX_END -->"
    block = f"{marker_start}\n{index_block}\n{marker_end}"

    if marker_start in content:
        # Replace existing block
        import re
        content = re.sub(
            rf"{re.escape(marker_start)}.*?{re.escape(marker_end)}",
            block,
            content,
            flags=re.DOTALL
        )
    else:
        # Append to end of file
        content = content.rstrip() + f"\n\n---\n\n{block}\n"

    with open(README_PATH, "w", encoding="utf-8") as fh:
        fh.write(content)

    print(f"README.md updated with {len(file_list)} file entries.")


if __name__ == "__main__":
    file_list = get_git_tracked_files()
    if file_list is None:
        print("git ls-files failed, falling back to filesystem walk.")
        file_list = walk_all_files()

    index_block = build_index(file_list)
    update_readme(index_block)
    write_index_txt(file_list)
    print("Done. Commit and push README.md and FILE_INDEX.txt to make the index live.")
