"""
ship_library.py
Read-only template data for the 5 canonical Psi-Wars ships.
The GM never edits this file directly. It is used to pre-fill ship records at scenario setup.
"""

SHIP_LIBRARY = {
    "javelin": {
        "library_key": "javelin",
        "name": "Javelin Class Fighter",
        "ship_class": "fighter",
        "faction": "imperial",
        "hp_max": 80,
        "hp_current": 80,
        "ht": 9,
        "sm": 4,
        "handling": 4,
        "sr": 3,
        "move_ground": 20,
        "move_space": 600,
        "stall_speed": 0,
        "dr_hull": 15,
        "force_screen_max": 500,
        "force_screen_current": 500,
        "force_screen_hardened": True,
        "afterburner_available": True,
        "afterburner_active": False,
        "afterburner_move_bonus": 150,
        "afterburner_chase_bonus": 15,
        "fuel_max": 100,
        "fuel_current": 100,
        "fuel_consumption_normal": 1,
        "fuel_consumption_afterburner": 4,
        "fuel_tracking_enforced": True,
        "ecm_rating": -4,
        "has_targeting_computer": True,
        "has_tactical_esm": True,
        "has_decoy_launcher": True,
        "has_ultrascanner": False,
        "sensor_lock_active": False,
        "wound_level": "none",
        "is_destroyed": False,
        "is_uncontrolled": False,
        "config_modes": [],
        "active_config": None,
        "notes": "",
        "weapons": [
            {
                "name": "Linked Fighter Blasters",
                "weapon_type": "gun",
                "mount_type": "fixed",
                "facings": ["F"],
                "damage_dice": 6,
                "damage_mult": 5,
                "damage_type": "burn",
                "armor_divisor": 5.0,
                "accuracy": 12,
                "rof": 6,
                "shots_max": 0,
                "shots_current": 0,
                "is_linked": True,
                "is_light_turret": False,
                "is_disabled": False,
            }
        ],
    },

    "peltast": {
        "library_key": "peltast",
        "name": "Peltast Class Striker",
        "ship_class": "fighter",
        "faction": "imperial",
        "hp_max": 85,
        "hp_current": 85,
        "ht": 10,
        "sm": 4,
        "handling": 3,
        "sr": 3,
        "move_ground": 10,
        "move_space": 450,
        "stall_speed": 20,
        "dr_hull": 15,
        "force_screen_max": 500,
        "force_screen_current": 500,
        "force_screen_hardened": True,
        "afterburner_available": True,
        "afterburner_active": False,
        "afterburner_move_bonus": 100,
        "afterburner_chase_bonus": 10,
        "fuel_max": 100,
        "fuel_current": 100,
        "fuel_consumption_normal": 1,
        "fuel_consumption_afterburner": 4,
        "fuel_tracking_enforced": True,
        "ecm_rating": -4,
        "has_targeting_computer": True,
        "has_tactical_esm": True,
        "has_decoy_launcher": True,
        "has_ultrascanner": False,
        "sensor_lock_active": False,
        "wound_level": "none",
        "is_destroyed": False,
        "is_uncontrolled": False,
        "config_modes": [],
        "active_config": None,
        "notes": "",
        "weapons": [
            {
                "name": "Linked Fighter Blasters",
                "weapon_type": "gun",
                "mount_type": "fixed",
                "facings": ["F"],
                "damage_dice": 6,
                "damage_mult": 5,
                "damage_type": "burn",
                "armor_divisor": 5.0,
                "accuracy": 12,
                "rof": 6,
                "shots_max": 0,
                "shots_current": 0,
                "is_linked": True,
                "is_light_turret": False,
                "is_disabled": False,
            },
            {
                "name": "Missile Hardpoints (160mm plasma)",
                "weapon_type": "missile",
                "mount_type": "fixed",
                "facings": ["F"],
                "damage_dice": 6,
                "damage_mult": 5,
                "damage_type": "burn",
                "armor_divisor": 5.0,
                "accuracy": 10,
                "rof": 1,
                "shots_max": 12,
                "shots_current": 12,
                "is_linked": False,
                "is_light_turret": False,
                "is_disabled": False,
            },
            {
                "name": "Isomeric Torpedo",
                "weapon_type": "torpedo",
                "mount_type": "fixed",
                "facings": ["F"],
                "damage_dice": 6,
                "damage_mult": 20,
                "damage_type": "burn",
                "armor_divisor": 5.0,
                "accuracy": 10,
                "rof": 1,
                "shots_max": 1,
                "shots_current": 1,
                "is_linked": False,
                "is_light_turret": False,
                "is_disabled": False,
            },
        ],
    },

    "hornet": {
        "library_key": "hornet",
        "name": "Hornet-Class Interceptor",
        "ship_class": "fighter",
        "faction": "trader",
        "hp_max": 95,
        "hp_current": 95,
        "ht": 13,
        "sm": 4,
        "handling": 6,
        "sr": 3,
        "move_ground": 15,
        "move_space": 500,
        "stall_speed": 0,
        "dr_hull": 10,
        "force_screen_max": 150,
        "force_screen_current": 150,
        "force_screen_hardened": True,
        "afterburner_available": False,
        "afterburner_active": False,
        "afterburner_move_bonus": 0,
        "afterburner_chase_bonus": 0,
        "fuel_max": 0,
        "fuel_current": 0,
        "fuel_consumption_normal": 0,
        "fuel_consumption_afterburner": 0,
        "fuel_tracking_enforced": False,
        "ecm_rating": -4,
        "has_targeting_computer": False,
        "has_tactical_esm": True,
        "has_decoy_launcher": False,
        "has_ultrascanner": False,
        "sensor_lock_active": False,
        "wound_level": "none",
        "is_destroyed": False,
        "is_uncontrolled": False,
        "config_modes": [
            {
                "key": "high_speed",
                "label": "High-Speed Mode",
                "handling": 6,
                "move_ground": 15,
                "move_space": 500,
                "chase_bonus": 20,
            },
            {
                "key": "high_maneuver",
                "label": "High-Maneuver Mode",
                "handling": 7,
                "move_ground": 3,
                "move_space": 250,
                "chase_bonus": 19,
            },
        ],
        "active_config": "high_speed",
        "notes": "Requires neural interface (pilot must have neural jack). Trader tech: -5 Mechanic penalty for non-Traders.",
        "weapons": [
            {
                "name": "Linked Muonic Cannons",
                "weapon_type": "gun",
                "mount_type": "fixed",
                "facings": ["F"],
                "damage_dice": 3,
                "damage_mult": 5,
                "damage_type": "burn",
                "armor_divisor": 10.0,
                "accuracy": 12,
                "rof": 16,
                "shots_max": 0,
                "shots_current": 0,
                "is_linked": True,
                "is_light_turret": False,
                "is_disabled": False,
            },
            {
                "name": "Particle Cannon Stinger",
                "weapon_type": "gun",
                "mount_type": "fixed",
                "facings": ["F"],
                "damage_dice": 6,
                "damage_mult": 15,
                "damage_type": "burn",
                "armor_divisor": 15.0,
                "accuracy": 14,
                "rof": 1,
                "shots_max": 0,
                "shots_current": 0,
                "is_linked": False,
                "is_light_turret": False,
                "is_disabled": False,
            },
        ],
    },

    "nomad_combat": {
        "library_key": "nomad_combat",
        "name": "Nomad-Class Corvette (Combat)",
        "ship_class": "corvette",
        "faction": "redjack",
        "hp_max": 225,
        "hp_current": 225,
        "ht": 13,
        "sm": 7,
        "handling": 2,
        "sr": 3,
        "move_ground": 7,
        "move_space": 300,
        "stall_speed": 0,
        "dr_hull": 150,
        "force_screen_max": 500,
        "force_screen_current": 500,
        "force_screen_hardened": True,
        "afterburner_available": False,
        "afterburner_active": False,
        "afterburner_move_bonus": 0,
        "afterburner_chase_bonus": 0,
        "fuel_max": 0,
        "fuel_current": 0,
        "fuel_consumption_normal": 0,
        "fuel_consumption_afterburner": 0,
        "fuel_tracking_enforced": False,
        "ecm_rating": -4,
        "has_targeting_computer": True,
        "has_tactical_esm": True,
        "has_decoy_launcher": True,
        "has_ultrascanner": False,
        "sensor_lock_active": False,
        "wound_level": "none",
        "is_destroyed": False,
        "is_uncontrolled": False,
        "config_modes": [],
        "active_config": None,
        "notes": "Blackout module: active jammer, ESM. Modular config locked for Slice 2.",
        "weapons": [
            {
                "name": "B00-M Heavy Plasma Cannon",
                "weapon_type": "gun",
                "mount_type": "fixed",
                "facings": ["F"],
                "damage_dice": 6,
                "damage_mult": 30,
                "damage_type": "burn",
                "armor_divisor": 5.0,
                "accuracy": 12,
                "rof": 1,
                "shots_max": 0,
                "shots_current": 0,
                "is_linked": False,
                "is_light_turret": False,
                "is_disabled": False,
            },
            {
                "name": "Modular Fighter Turrets (×4)",
                "weapon_type": "gun",
                "mount_type": "turret",
                "facings": ["F", "R", "L", "B", "U", "D"],
                "damage_dice": 6,
                "damage_mult": 5,
                "damage_type": "burn",
                "armor_divisor": 5.0,
                "accuracy": 12,
                "rof": 6,
                "shots_max": 0,
                "shots_current": 0,
                "is_linked": False,
                "is_light_turret": True,
                "is_disabled": False,
            },
            {
                "name": "Rear Tractor Beam",
                "weapon_type": "gun",
                "mount_type": "turret",
                "facings": ["B"],
                "damage_dice": 0,
                "damage_mult": 1,
                "damage_type": "cr",
                "armor_divisor": 1.0,
                "accuracy": 10,
                "rof": 1,
                "shots_max": 0,
                "shots_current": 0,
                "is_linked": False,
                "is_light_turret": False,
                "is_disabled": False,
            },
        ],
    },

    "tigershark": {
        "library_key": "tigershark",
        "name": "Tigershark Assault Corvette",
        "ship_class": "corvette",
        "faction": "redjack",
        "hp_max": 400,
        "hp_current": 400,
        "ht": 14,
        "sm": 8,
        "handling": 2,
        "sr": 3,
        "move_ground": 6,
        "move_space": 250,
        "stall_speed": 0,
        "dr_hull": 1000,
        "force_screen_max": 750,
        "force_screen_current": 750,
        "force_screen_hardened": True,
        "afterburner_available": False,
        "afterburner_active": False,
        "afterburner_move_bonus": 0,
        "afterburner_chase_bonus": 0,
        "fuel_max": 0,
        "fuel_current": 0,
        "fuel_consumption_normal": 0,
        "fuel_consumption_afterburner": 0,
        "fuel_tracking_enforced": False,
        "ecm_rating": 0,
        "has_targeting_computer": True,
        "has_tactical_esm": False,
        "has_decoy_launcher": False,
        "has_ultrascanner": False,
        "sensor_lock_active": False,
        "wound_level": "none",
        "is_destroyed": False,
        "is_uncontrolled": False,
        "config_modes": [],
        "active_config": None,
        "notes": "Rear hardpoints empty. Hyperdrive Rating 2 (7 shunts). 30-day endurance.",
        "weapons": [
            {
                "name": "Forward Corvette Cannon",
                "weapon_type": "gun",
                "mount_type": "fixed",
                "facings": ["F"],
                "damage_dice": 6,
                "damage_mult": 30,
                "damage_type": "burn",
                "armor_divisor": 5.0,
                "accuracy": 12,
                "rof": 2,
                "shots_max": 0,
                "shots_current": 0,
                "is_linked": False,
                "is_light_turret": False,
                "is_disabled": False,
            },
            {
                "name": "Fighter Turrets (×4)",
                "weapon_type": "gun",
                "mount_type": "turret",
                "facings": ["F", "R", "L", "B", "U", "D"],
                "damage_dice": 6,
                "damage_mult": 5,
                "damage_type": "burn",
                "armor_divisor": 5.0,
                "accuracy": 12,
                "rof": 6,
                "shots_max": 0,
                "shots_current": 0,
                "is_linked": False,
                "is_light_turret": True,
                "is_disabled": False,
            },
            {
                "name": "Rear Tractor Beam (ST 160)",
                "weapon_type": "gun",
                "mount_type": "turret",
                "facings": ["B"],
                "damage_dice": 0,
                "damage_mult": 1,
                "damage_type": "cr",
                "armor_divisor": 1.0,
                "accuracy": 10,
                "rof": 1,
                "shots_max": 0,
                "shots_current": 0,
                "is_linked": False,
                "is_light_turret": False,
                "is_disabled": False,
            },
        ],
    },
}

SYSTEM_NAMES = [
    "armor",
    "cargo",
    "controls",
    "equipment",
    "fuel",
    "habitat",
    "power",
    "propulsion",
    "weaponry",
]
